<?php

namespace Database\Seeders;

use App\Models\Author;
use App\Models\Category;
use App\Models\Keyword;
use App\Models\Publisher;
use App\Models\Reference;
use App\Models\User;
use Illuminate\Database\Seeder;

class ReferenceSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::pluck('id', 'name')->toArray();
        $publisherIds = Publisher::pluck('id')->toArray();
        $userIds = User::pluck('id')->toArray();
        $authorIds = Author::pluck('id')->toArray();
        $keywordIds = Keyword::pluck('id')->toArray();

        $references = [
            [
                'title' => 'Droit constitutionnel béninois',
                'subtitle' => 'Principes fondamentaux et évolution',
                'abstract' => 'Cet ouvrage présente les principes fondamentaux du droit constitutionnel au Bénin, retraçant l\'évolution des institutions depuis l\'indépendance jusqu\'à la période contemporaine.',
                'isbn' => '978-2-247-12345-6',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Droit',
                'pages' => 320,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Les fondements du droit des affaires en Afrique',
                'subtitle' => 'OHADA et pratiques commerciales',
                'abstract' => 'Analyse complète du droit des affaires dans l\'espace OHADA, avec une étude des pratiques commerciales et des mécanismes de règlement des litiges.',
                'isbn' => '978-2-247-23456-7',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Droit',
                'pages' => 450,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Introduction au droit foncier au Bénin',
                'subtitle' => null,
                'abstract' => 'Guide pratique sur la législation foncière béninoise, les procédures d\'immatriculation et les conflits fonciers.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'guide',
                'category' => 'Droit',
                'pages' => 180,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Physique quantique pour débutants',
                'subtitle' => 'Une introduction accessible',
                'abstract' => 'Introduction claire et pédagogique aux concepts de la physique quantique, destinée aux étudiants en sciences.',
                'isbn' => '978-2-130-34567-8',
                'publication_year' => 2019,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Sciences',
                'pages' => 280,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Chimie organique fondamentale',
                'subtitle' => 'Réactions et mécanismes',
                'abstract' => 'Manuel de chimie organique couvrant les principales réactions et leurs mécanismes, avec des exercices corrigés.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Sciences',
                'pages' => 390,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Mathématiques appliquées à l\'économie',
                'subtitle' => 'Optimisation et modélisation',
                'abstract' => 'Les outils mathématiques essentiels pour l\'analyse économique : optimisation, calcul différentiel et modélisation.',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Sciences',
                'pages' => 310,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Histoire du Bénin des origines à nos jours',
                'subtitle' => 'Le royaume du Dahomey et la République',
                'abstract' => 'Vaste fresque historique retraçant l\'histoire du Bénin depuis les premiers peuplements jusqu\'à la période contemporaine, en passant par le glorieux royaume du Dahomey.',
                'isbn' => '978-2-296-45678-9',
                'publication_year' => 2018,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Histoire',
                'pages' => 520,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Les royautés africaines précoloniales',
                'subtitle' => 'Organisation politique et sociale',
                'abstract' => 'Étude comparative des grandes royautés africaines avant la colonisation : structures politiques, systèmes de gouvernance et héritage culturel.',
                'publication_year' => 2019,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Histoire',
                'pages' => 380,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'La colonisation française en Afrique de l\'Ouest',
                'subtitle' => 'Mécanismes et résistances',
                'abstract' => 'Analyse des mécanismes de la colonisation française en Afrique de l\'Ouest et des mouvements de résistance qui ont émergé.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'these',
                'category' => 'Histoire',
                'pages' => 420,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Médecine tropicale : maladies endémiques',
                'subtitle' => 'Diagnostic et prise en charge',
                'abstract' => 'Guide exhaustif sur les maladies tropicales les plus courantes en Afrique subsaharienne, avec protocoles de diagnostic et de traitement.',
                'isbn' => '978-2-840-56789-0',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Médecine',
                'pages' => 560,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Santé publique en Afrique subsaharienne',
                'subtitle' => 'Défis et perspectives',
                'abstract' => 'État des lieux des systèmes de santé en Afrique subsaharienne, analyse des défis et propositions pour l\'avenir.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'article',
                'category' => 'Médecine',
                'pages' => 25,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Guide de pédiatrie tropicale',
                'subtitle' => 'Soins essentiels du nouveau-né et de l\'enfant',
                'abstract' => 'Manuel pratique destiné aux professionnels de santé exerçant en milieu tropical, couvrant les pathologies pédiatriques courantes.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'guide',
                'category' => 'Médecine',
                'pages' => 340,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Une si longue lettre',
                'subtitle' => null,
                'abstract' => 'Roman épistolaire qui dépeint la condition féminine dans la société sénégalaise à travers la correspondance de deux femmes.',
                'isbn' => '978-2-708-71234-5',
                'publication_year' => 2019,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Littérature',
                'pages' => 160,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Les soleils des indépendances',
                'subtitle' => null,
                'abstract' => 'Roman satirique sur les désillusions de l\'indépendance dans un pays africain imaginaire.',
                'publication_year' => 2018,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Littérature',
                'pages' => 200,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'L\'aventure ambiguë',
                'subtitle' => null,
                'abstract' => 'Roman philosophique sur le choc des cultures entre l\'Afrique et l\'Occident à travers le parcours d\'un jeune Sénégalais.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Littérature',
                'pages' => 190,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Économie du développement en Afrique',
                'subtitle' => 'Théories et pratiques',
                'abstract' => 'Analyse des théories du développement et de leur application au contexte africain, avec des études de cas.',
                'isbn' => '978-2-130-45678-9',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Économie',
                'pages' => 350,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Microfinance et inclusion financière',
                'subtitle' => 'Le cas de l\'Afrique de l\'Ouest',
                'abstract' => 'Étude approfondie des systèmes de microfinance en Afrique de l\'Ouest et de leur impact sur l\'inclusion financière.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'memoire',
                'category' => 'Économie',
                'pages' => 120,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Commerce international et mondialisation',
                'subtitle' => 'Enjeux pour les pays en développement',
                'abstract' => 'Analyse des mécanismes du commerce international et de leurs impacts sur les économies des pays en développement.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Économie',
                'pages' => 290,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Philosophie africaine : sagesse et modernité',
                'subtitle' => 'Penser l\'Afrique d\'aujourd\'hui',
                'abstract' => 'Réflexion sur la philosophie africaine contemporaine, entre traditions ancestrales et défis de la modernité.',
                'isbn' => '978-2-296-56789-0',
                'publication_year' => 2019,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Philosophie',
                'pages' => 240,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Éthique et développement durable',
                'subtitle' => 'Une perspective africaine',
                'abstract' => 'Essai sur l\'éthique du développement durable vu à travers le prisme des valeurs africaines traditionnelles.',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'article',
                'category' => 'Philosophie',
                'pages' => 18,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Introduction à l\'intelligence artificielle',
                'subtitle' => 'Concepts et applications',
                'abstract' => 'Vue d\'ensemble des concepts fondamentaux de l\'intelligence artificielle et de ses applications dans divers domaines.',
                'isbn' => '978-2-840-67890-1',
                'publication_year' => 2023,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Informatique',
                'pages' => 400,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Développement web avec Laravel',
                'subtitle' => 'De zéro à déploiement',
                'abstract' => 'Guide complet pour apprendre le développement web avec le framework Laravel, de la création d\'un projet au déploiement.',
                'publication_year' => 2023,
                'language' => 'fr',
                'document_type' => 'guide',
                'category' => 'Informatique',
                'pages' => 350,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Bases de données et Big Data',
                'subtitle' => 'Architectures et optimisation',
                'abstract' => 'Étude des systèmes de gestion de bases de données relationnelles et des technologies Big Data.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Informatique',
                'pages' => 310,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Sociologie urbaine des villes africaines',
                'subtitle' => 'Dynamiques et mutations',
                'abstract' => 'Analyse des transformations sociales et urbaines dans les grandes villes africaines contemporaines.',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Sociologie',
                'pages' => 270,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Genre et développement en Afrique',
                'subtitle' => 'Vers l\'égalité des chances',
                'abstract' => 'Étude des inégalités de genre en Afrique et des politiques de développement visant à promouvoir l\'égalité.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'rapport',
                'category' => 'Sociologie',
                'pages' => 85,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Géographie du Bénin',
                'subtitle' => 'Milieux naturels et aménagement',
                'abstract' => 'Présentation complète de la géographie physique et humaine du Bénin, avec une analyse des enjeux d\'aménagement du territoire.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Géographie',
                'pages' => 230,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Changement climatique en Afrique de l\'Ouest',
                'subtitle' => 'Impacts et stratégies d\'adaptation',
                'abstract' => 'Analyse des impacts du changement climatique en Afrique de l\'Ouest et des stratégies d\'adaptation mises en œuvre.',
                'publication_year' => 2023,
                'language' => 'fr',
                'document_type' => 'article',
                'category' => 'Géographie',
                'pages' => 22,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Relations internationales en Afrique',
                'subtitle' => 'Diplomatie et conflits',
                'abstract' => 'Analyse des relations internationales sur le continent africain, des dynamiques diplomatiques aux conflits régionaux.',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Sciences Politiques',
                'pages' => 360,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Gouvernance et démocratie en Afrique',
                'subtitle' => 'Bilan et perspectives',
                'abstract' => 'Bilan critique des processus de démocratisation en Afrique et des défis de la gouvernance contemporaine.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'revue',
                'category' => 'Sciences Politiques',
                'pages' => 45,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Les arts contemporains africains',
                'subtitle' => 'Création et reconnaissance internationale',
                'abstract' => 'Exploration de la scène artistique africaine contemporaine et de sa reconnaissance sur la scène internationale.',
                'publication_year' => 2023,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Arts',
                'pages' => 200,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Agriculture durable en Afrique tropicale',
                'subtitle' => 'Innovations et pratiques',
                'abstract' => 'Guide des pratiques agricoles durables adaptées au contexte tropical africain, avec des retours d\'expérience de terrain.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'guide',
                'category' => 'Sciences',
                'pages' => 190,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Droits de l\'homme en Afrique',
                'subtitle' => 'Mécanismes de protection et défis',
                'abstract' => 'Analyse des mécanismes régionaux et internationaux de protection des droits de l\'homme en Afrique.',
                'publication_year' => 2021,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Droit',
                'pages' => 410,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Entrepreneuriat et innovation en Afrique',
                'subtitle' => 'Écosystèmes et opportunités',
                'abstract' => 'État des lieux de l\'entrepreneuriat en Afrique, des écosystèmes d\'innovation et des opportunités pour les jeunes.',
                'publication_year' => 2023,
                'language' => 'fr',
                'document_type' => 'rapport',
                'category' => 'Économie',
                'pages' => 95,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Éducation et développement en Afrique',
                'subtitle' => 'Quels modèles pour le XXIe siècle ?',
                'abstract' => 'Réflexion sur les systèmes éducatifs africains et les modèles pédagogiques adaptés aux défis contemporains.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'memoire',
                'category' => 'Sociologie',
                'pages' => 110,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Les technologies mobiles en Afrique',
                'subtitle' => 'Usages et impacts socio-économiques',
                'abstract' => 'Étude de la révolution mobile en Afrique et de son impact sur les secteurs économique, social et culturel.',
                'publication_year' => 2022,
                'language' => 'fr',
                'document_type' => 'article',
                'category' => 'Technologie',
                'pages' => 15,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Législation du travail dans l\'espace UEMOA',
                'subtitle' => null,
                'abstract' => 'Synthèse de la législation du travail en vigueur dans les pays de l\'UEMOA, à l\'usage des praticiens.',
                'publication_year' => 2020,
                'language' => 'fr',
                'document_type' => 'livre',
                'category' => 'Droit',
                'pages' => 280,
                'is_featured' => false,
                'status' => 'published',
            ],
        ];

        foreach ($references as $data) {
            $categoryName = $data['category'];
            unset($data['category']);

            $reference = Reference::factory()->create(array_merge($data, [
                'category_id' => $categories[$categoryName] ?? Category::factory(),
                'publisher_id' => $publisherIds[array_rand($publisherIds)],
                'uploaded_by' => $userIds[array_rand($userIds)],
            ]));

            $selectedAuthors = (array) array_rand(array_flip($authorIds), rand(1, 3));
            $reference->authors()->attach($selectedAuthors);

            $selectedKeywords = (array) array_rand(array_flip($keywordIds), rand(2, 5));
            $reference->keywords()->attach($selectedKeywords);
        }

        $this->command->info('References seeded successfully.');
    }
}
